name: emulator_playstation_2
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/LionelOsricNelson/emulator_playstation_2
repository: https://github.com/LionelOsricNelson/emulator_playstation_2
issue_tracker: https://github.com/LionelOsricNelson/emulator_playstation_2/issues 
documentation: https://youtube.com/@LionelOsricNelson
funding:
  - https://github.com/sponsors/LionelOsricNelson


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - emulator_playstation_2
#   - emulator_playstation_2_flutter
#   - emulator_playstation_2_dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
